export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ALL_PRODUCTS_NAME = 'FETCH_ALL_PRODUCTS_NAME';
export const SELECT_A_PRODUCT = 'SELECT_A_PRODUCT';
export const LOADING = 'LOADING';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ALL_PRODUCTS_FROM_CART = 'REMOVE_ALL_PRODUCTS_FROM_CART';
export const FETCH_TAXES = 'FETCH_TAXES';
export const FETCH_SHIPPING_REGIONS = 'FETCH_SHIPPING_REGIONS';
export const FETCH_SHIPPING_REGION_DETAIL = 'FETCH_SHIPPING_REGION_DETAIL';