export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ALL_PRODUCTS_NAME = 'FETCH_ALL_PRODUCTS_NAME';
export const SELECT_A_PRODUCT = 'SELECT_A_PRODUCT';
export const MAKE_A_SEARCH = 'MAKE_A_SEARCH';
export const RESET = 'RESET';